name: Docker Image CI

on:
  push:
    branches: [ aarch64 ]
  pull_request:
    branches: [ aarch64]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag stf-aarch64:$(date +%s)
       
    - name: Log in to Docker Hub
    - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
